// words.js : 時制単語特訓 データファイル (中学生・高校受験仕様 v3.21)

// 1. 重要語データ（詳細例文付き）
const importantWords = [
    // --- Regular Verbs ---
    { forms: { basic: "play", past: "played", ing: "playing", pp: "played" }, type: "regular", sentences: { present: { jp: "私は普段、週末にテニスを[する]。", en: "I usually [ _____ ] tennis on weekends." }, past: { jp: "私は昨日、友達と[遊んだ]。", en: "I [ _____ ] with my friends yesterday." }, future: { jp: "私は明日、弟とゲームを[するつもりだ]。", en: "I [ _____ ] video games with my brother tomorrow." }, prog: { jp: "私は今、公園で[遊んでいる]。", en: "I am [ _____ ] in the park now." }, pastprog: { jp: "私はその時、ギターを[弾いていた]。", en: "I was [ _____ ] the guitar then." }, perf: { jp: "私はちょうどそのゲームを[し終えた]ところだ。", en: "I have just [ _____ ] that game." } } },
    { forms: { basic: "go", past: "went", ing: "going", pp: "gone" }, type: "irregular", memo: "不規則変化: go-went-gone", sentences: { present: { jp: "私は普段、バスで学校へ[行く]。", en: "I usually [ _____ ] to school by bus." }, past: { jp: "私は先週の日曜日、動物園へ[行った]。", en: "I [ _____ ] to the zoo last Sunday." }, future: { jp: "私は来月、京都へ[行くつもりだ]。", en: "I [ _____ ] to Kyoto next month." }, prog: { jp: "私は今、駅へ向かって[行っている]ところだ。", en: "I am [ _____ ] to the station now." }, perf: { jp: "彼はもうアメリカへ[行ってしまった]。(ここにはいない)", en: "He has already [ _____ ] to America." } } },
    { forms: { basic: "study", past: "studied", ing: "studying", pp: "studied" }, type: "y_change", memo: "yをiに変えてed", sentences: { present: { jp: "私は毎日、英語を[勉強する]。", en: "I [ _____ ] English every day." }, past: { jp: "私は昨夜、遅くまで[勉強した]。", en: "I [ _____ ] till late last night." }, prog: { jp: "弟は今、部屋で[勉強している]。", en: "My brother is [ _____ ] in his room now." }, perf: { jp: "私は3年間、フランス語を[勉強している](継続)。", en: "I have [ _____ ] French for three years." } } },
    { forms: { basic: "watch", past: "watched", ing: "watching", pp: "watched" }, type: "regular", sentences: { present: { jp: "私は毎晩ニュースを[見る]。", en: "I [ _____ ] the news every night." }, past: { jp: "昨夜その映画を[見た]。", en: "I [ _____ ] that movie last night." }, prog: { jp: "今テレビを[見ている]。", en: "I am [ _____ ] TV now." }, perf: { jp: "それを何度も[見たことがある]。", en: "I have [ _____ ] it many times." } } },
    { forms: { basic: "eat", past: "ate", ing: "eating", pp: "eaten" }, type: "irregular", sentences: { present: { jp: "毎朝朝食を[食べる]。", en: "I [ _____ ] breakfast every morning." }, past: { jp: "ランチにパスタを[食べた]。", en: "I [ _____ ] pasta for lunch." }, prog: { jp: "今夕食を[食べている]。", en: "I am [ _____ ] dinner now." }, perf: { jp: "カエルを[食べたことがある]。", en: "I have [ _____ ] frogs before." } } },
    { forms: { basic: "buy", past: "bought", ing: "buying", pp: "bought" }, type: "irregular", sentences: { past: { jp: "昨日新しい本を[買った]。", en: "I [ _____ ] a new book yesterday." }, future: { jp: "明日それを[買うつもりだ]。", en: "I [ _____ ] it tomorrow." }, perf: { jp: "ちょうどチケットを[買った]。", en: "I have just [ _____ ] the ticket." } } },
    { forms: { basic: "cook", past: "cooked", ing: "cooking", pp: "cooked" }, type: "regular", sentences: { present: { jp: "私の父はよく夕食を[作る(料理する)]。", en: "My father often [ _____ ] dinner." }, past: { jp: "私は昨夜、カレーを[作った]。", en: "I [ _____ ] curry last night." }, prog: { jp: "母は今、キッチンで[料理している]。", en: "My mother is [ _____ ] in the kitchen now." } } },
    { forms: { basic: "visit", past: "visited", ing: "visiting", pp: "visited" }, type: "regular", sentences: { present: { jp: "私は毎年、祖父母を[訪れる]。", en: "I [ _____ ] my grandparents every year." }, past: { jp: "私は先週、京都を[訪れた]。", en: "I [ _____ ] Kyoto last week." }, prog: { jp: "私は今、博物館を[訪れている]。", en: "I am [ _____ ] the museum now." } } },
    { forms: { basic: "walk", past: "walked", ing: "walking", pp: "walked" }, type: "regular", sentences: { present: { jp: "私は毎日、学校へ[歩く]。", en: "I [ _____ ] to school every day." }, past: { jp: "私は昨日、駅まで[歩いた]。", en: "I [ _____ ] to the station yesterday." }, prog: { jp: "彼らは今、通りを[歩いている]。", en: "They are [ _____ ] down the street." } } },
    { forms: { basic: "listen", past: "listened", ing: "listening", pp: "listened" }, type: "regular", sentences: { present: { jp: "私は寝る前に音楽を[聴く]。", en: "I [ _____ ] to music before bed." }, past: { jp: "私はその講義を注意深く[聴いた]。", en: "I [ _____ ] to the lecture carefully." }, prog: { jp: "私は今、ラジオを[聴いている]。", en: "I am [ _____ ] to the radio now." } } },
    // --- e-drop ---
    { forms: { basic: "use", past: "used", ing: "using", pp: "used" }, type: "e_drop", sentences: { present: { jp: "私は毎日、このコンピュータを[使う]。", en: "I [ _____ ] this computer every day." }, past: { jp: "私は昨日、あなたのペンを[使った]。", en: "I [ _____ ] your pen yesterday." }, prog: { jp: "私は今、辞書を[使っている]。", en: "I am [ _____ ] a dictionary now." }, perf: { jp: "私はそのアプリを一度も[使ったことがない]。", en: "I have never [ _____ ] that app." } } },
    { forms: { basic: "make", past: "made", ing: "making", pp: "making", pp: "made" }, type: "e_drop_irreg", sentences: { present: { jp: "彼女はよくケーキを[作る]。", en: "She often [ _____ ] cakes." }, past: { jp: "母は私に新しいドレスを[作ってくれた]。", en: "My mother [ _____ ] me a new dress." }, prog: { jp: "彼らは今、大きな音を[立てている]。", en: "They are [ _____ ] a loud noise now." }, perf: { jp: "私はちょうどサンドイッチを[作った]ところだ。", en: "I have just [ _____ ] some sandwiches." } } },
    { forms: { basic: "write", past: "wrote", ing: "writing", pp: "written" }, type: "e_drop_irreg", sentences: { present: { jp: "私は毎週、祖母に手紙を[書く]。", en: "I [ _____ ] a letter to my grandmother every week." }, past: { jp: "シェイクスピアは多くの劇を[書いた]。", en: "Shakespeare [ _____ ] many plays." }, prog: { jp: "私は今、レポートを[書いている]。", en: "I am [ _____ ] a report now." }, perf: { jp: "私は彼にまだ返事を[書いていない]。", en: "I haven't [ _____ ] back to him yet." } } },
    { forms: { basic: "take", past: "took", ing: "taking", pp: "taken" }, type: "e_drop_irreg", sentences: { past: { jp: "私は昨日、たくさんの写真を[撮った]。", en: "I [ _____ ] many pictures yesterday." }, future: { jp: "私は明日、その試験を[受けるつもりだ]。", en: "I [ _____ ] the exam tomorrow." }, prog: { jp: "彼は今、お風呂に[入っている]。", en: "He is [ _____ ] a bath now." } } },
    { forms: { basic: "live", past: "lived", ing: "living", pp: "lived" }, type: "e_drop", sentences: { present: { jp: "私は日本に[住んでいる]。", en: "I [ _____ ] in Japan." }, past: { jp: "私は以前、東京に[住んでいた]。", en: "I [ _____ ] in Tokyo before." }, perf: { jp: "私は5年前からずっとここに[住んでいる]。", en: "I have [ _____ ] here for five years." } } },
    { forms: { basic: "come", past: "came", ing: "coming", pp: "come" }, type: "e_drop_irreg", sentences: { present: { jp: "春が[来る]。", en: "Spring [ _____ ]s." }, past: { jp: "彼らは昨日、私の家に[来た]。", en: "They [ _____ ] to my house yesterday." }, prog: { jp: "電車が[やって来ている]。", en: "The train is [ _____ ]." } } },
    // --- Double Consonant ---
    { forms: { basic: "run", past: "ran", ing: "running", pp: "run" }, type: "double_c", sentences: { present: { jp: "チーターはとても速く[走る]。", en: "Cheetahs [ _____ ] very fast." }, past: { jp: "彼は昨日、学校まで[走った]。", en: "He [ _____ ] to school yesterday." }, prog: { jp: "犬が公園を[走っている]。", en: "The dog is [ _____ ] in the park." } } },
    { forms: { basic: "stop", past: "stopped", ing: "stopping", pp: "stopped" }, type: "double_c", sentences: { present: { jp: "このバスはその駅には[止まらない]。", en: "This bus doesn't [ _____ ] at that station." }, past: { jp: "雨は数分前に[止んだ]。", en: "The rain [ _____ ] a few minutes ago." }, prog: { jp: "バスがバス停に[止まろうとしている]。", en: "The bus is [ _____ ] at the bus stop." } } },
    { forms: { basic: "swim", past: "swam", ing: "swimming", pp: "swum" }, type: "double_c", sentences: { present: { jp: "私は夏に海で[泳ぐ]。", en: "I [ _____ ] in the sea in summer." }, past: { jp: "私は昨日、プールで[泳いだ]。", en: "I [ _____ ] in the pool yesterday." }, prog: { jp: "彼は今、川で[泳いでいる]。", en: "He is [ _____ ] in the river." } } },
    { forms: { basic: "get", past: "got", ing: "getting", pp: "gotten" }, type: "double_c_irreg", sentences: { past: { jp: "私は昨日、新しい自転車を[手に入れた]。", en: "I [ _____ ] a new bicycle yesterday." }, prog: { jp: "外は暗くなって[きている]。", en: "It is [ _____ ] dark outside." }, perf: { jp: "彼はもう[起きた(起きた状態だ)]。", en: "He has [ _____ ] up already." } } },
    { forms: { basic: "cut", past: "cut", ing: "cutting", pp: "cut" }, type: "double_c_same", sentences: { present: { jp: "このナイフはよく[切れる]。", en: "This knife [ _____ ]s well." }, past: { jp: "私は昨日、髪を[切った]。", en: "I [ _____ ] my hair yesterday." }, prog: { jp: "母は今、野菜を[切っている]。", en: "My mother is [ _____ ] vegetables now." } } },
    { forms: { basic: "put", past: "put", ing: "putting", pp: "put" }, type: "double_c_same", sentences: { present: { jp: "私はいつもここに鍵を[置く]。", en: "I always [ _____ ] my keys here." }, past: { jp: "私は昨日、かばんをそこに[置いた]。", en: "I [ _____ ] my bag there yesterday." }, prog: { jp: "彼は今、コートを[着ている(身につけている)]。", en: "He is [ _____ ] on his coat." } } },
    // --- y change ---
    { forms: { basic: "cry", past: "cried", ing: "crying", pp: "cried" }, type: "y_change", sentences: { past: { jp: "赤ちゃんは昨夜、たくさん[泣いた]。", en: "The baby [ _____ ] a lot last night." }, prog: { jp: "なぜあなたは[泣いている]のですか？", en: "Why are you [ _____ ]?" } } },
    { forms: { basic: "try", past: "tried", ing: "trying", pp: "tried" }, type: "y_change", sentences: { past: { jp: "私はそのドアを開けようと[試みた]。", en: "I [ _____ ] to open the door." }, prog: { jp: "私は最善を[尽くしている]。", en: "I am [ _____ ] my best." } } },
    // --- Irregular ---
    { forms: { basic: "do", past: "did", ing: "doing", pp: "done" }, type: "irregular", sentences: { present: { jp: "私はいつも夕食前に宿題を[する]。", en: "I always [ _____ ] my homework before dinner." }, past: { jp: "私は昨日、その仕事を[した]。", en: "I [ _____ ] the work yesterday." }, perf: { jp: "私はもう宿題を[終えてしまった]。", en: "I have already [ _____ ] my homework." } } },
    { forms: { basic: "have", past: "had", ing: "having", pp: "had" }, type: "irregular", sentences: { present: { jp: "私は車を[持っている]。", en: "I [ _____ ] a car." }, past: { jp: "私は今朝、楽しい時間を[過ごした]。", en: "I [ _____ ] a good time this morning." }, perf: { jp: "私は以前、犬を[飼っていたことがある]。", en: "I have [ _____ ] a dog before." } } },
    { forms: { basic: "see", past: "saw", ing: "seeing", pp: "seen" }, type: "irregular", sentences: { past: { jp: "私は昨日、公園で彼を[見かけた]。", en: "I [ _____ ] him in the park yesterday." }, perf: { jp: "私はその映画を一度も[見たことがない]。", en: "I have never [ _____ ] that movie." } } },
    { forms: { basic: "speak", past: "spoke", ing: "speaking", pp: "spoken" }, type: "irregular", sentences: { present: { jp: "彼は英語とフランス語を[話す]。", en: "He [ _____ ]s English and French." }, past: { jp: "私は昨日、彼と電話で[話した]。", en: "I [ _____ ] with him on the phone yesterday." }, perf: { jp: "私は外国人と[話したことがある]。", en: "I have [ _____ ] to a foreigner before." } } },
    { forms: { basic: "read", past: "read", ing: "reading", pp: "read" }, type: "irregular_same", sentences: { present: { jp: "私は毎朝新聞を[読む]。", en: "I [ _____ ] the newspaper every morning." }, past: { jp: "私は昨夜、その本を[読んだ]。", en: "I [ _____ ] the book last night." }, perf: { jp: "私はもうその記事を[読んでしまった]。", en: "I have already [ _____ ] the article." } } },
    { forms: { basic: "meet", past: "met", ing: "meeting", pp: "met" }, type: "irregular", sentences: { past: { jp: "私は昨日、駅で彼女に[会った]。", en: "I [ _____ ] her at the station yesterday." }, future: { jp: "明日、私たちは１時に[会う予定だ]。", en: "We [ _____ ] at one o'clock tomorrow." } } },
    { forms: { basic: "sleep", past: "slept", ing: "sleeping", pp: "slept" }, type: "irregular", sentences: { present: { jp: "私は普段、10時に[寝る]。", en: "I usually [ _____ ] at ten." }, past: { jp: "私は昨夜よく[眠った]。", en: "I [ _____ ] well last night." }, prog: { jp: "赤ちゃんは今[眠っている]。", en: "The baby is [ _____ ] now." } } },
    { forms: { basic: "give", past: "gave", ing: "giving", pp: "given" }, type: "e_drop", sentences: { past: { jp: "彼は私にプレゼントを[くれた]。", en: "He [ _____ ] me a present." }, perf: { jp: "私はもう彼にお金を[渡した]。", en: "I have already [ _____ ] him the money." } } },
    { forms: { basic: "teach", past: "taught", ing: "teaching", pp: "taught" }, type: "irregular", sentences: { present: { jp: "彼女は私たちに英語を[教える]。", en: "She [ _____ ]es us English." }, past: { jp: "父が私に泳ぎ方を[教えてくれた]。", en: "My father [ _____ ] me how to swim." } } },
    { forms: { basic: "know", past: "knew", ing: "knowing", pp: "known" }, type: "irregular_state", sentences: { present: { jp: "私は彼の名前を[知る(知っている)]。", en: "I [ _____ ] his name." }, perf: { jp: "私は彼を10年間ずっと[知っている]。", en: "I have [ _____ ] him for ten years." } } },
    { forms: { basic: "think", past: "thought", ing: "thinking", pp: "thought" }, type: "irregular", sentences: { present: { jp: "私はそう[思う]。", en: "I [ _____ ] so." }, past: { jp: "私はそれが真実だと[思った]。", en: "I [ _____ ] it was true." }, prog: { jp: "私は今、あなたの提案について[考えている]。", en: "I am [ _____ ] about your proposal." } } },
    { forms: { basic: "find", past: "found", ing: "finding", pp: "found" }, type: "irregular", sentences: { past: { jp: "私は道で財布を[見つけた]。", en: "I [ _____ ] a wallet on the street." }, perf: { jp: "私は鍵を[見つけた]。", en: "I have [ _____ ] my key." } } },
    { forms: { basic: "lose", past: "lost", ing: "losing", pp: "lost" }, type: "e_drop", sentences: { past: { jp: "私は昨日、傘を[なくした]。", en: "I [ _____ ] my umbrella yesterday." }, perf: { jp: "私はチケットを[なくしてしまった]。", en: "I have [ _____ ] my ticket." } } },
    { forms: { basic: "stand", past: "stood", ing: "standing", pp: "stood" }, type: "irregular", sentences: { past: { jp: "彼はドアのそばに[立っていた]。", en: "He [ _____ ] by the door." }, prog: { jp: "誰かが門のところに[立っている]。", en: "Someone is [ _____ ] at the gate." } } },
    { forms: { basic: "send", past: "sent", ing: "sending", pp: "sent" }, type: "irregular", sentences: { past: { jp: "私は昨日、彼にメールを[送った]。", en: "I [ _____ ] him an email yesterday." }, perf: { jp: "私はまだ荷物を[送っていない]。", en: "I haven't [ _____ ] the package yet." } } },
    { forms: { basic: "show", past: "showed", ing: "showing", pp: "shown" }, type: "irregular", sentences: { past: { jp: "彼は私にパスポートを[見せた]。", en: "He [ _____ ] me his passport." }, perf: { jp: "私は先生に宿題を[見せた]。", en: "I have [ _____ ] my homework to the teacher." } } },
    { forms: { basic: "hold", past: "held", ing: "holding", pp: "held" }, type: "irregular", sentences: { past: { jp: "彼女は赤ちゃんを[抱いた]。", en: "She [ _____ ] the baby." }, prog: { jp: "彼は手に花を[持っている]。", en: "He is [ _____ ] flowers in his hand." } } },
    { forms: { basic: "tell", past: "told", ing: "telling", pp: "told" }, type: "irregular", sentences: { past: { jp: "彼は私に真実を[話した]。", en: "He [ _____ ] me the truth." }, prog: { jp: "私はあなたに嘘を[言っていない]。", en: "I'm not [ _____ ] you a lie." } } },
    { forms: { basic: "break", past: "broke", ing: "breaking", pp: "broken" }, type: "irregular", sentences: { past: { jp: "私は昨日、カップを[割った]。", en: "I [ _____ ] a cup yesterday." }, perf: { jp: "誰かが窓を[割った]。", en: "Someone has [ _____ ] the window." } } },
    { forms: { basic: "win", past: "won", ing: "winning", pp: "won" }, type: "double_c", sentences: { past: { jp: "私たちが試合に[勝った]。", en: "We [ _____ ] the game." }, perf: { jp: "彼は賞を[とったことがある]。", en: "He has [ _____ ] a prize." } } }
];

// 2. 拡張語リスト（自動活用のバグを防ぐため、日本語は「辞書形」で登録）
const extraWordsSimple = [
    {name:"agree",jp:"同意する",p:"agreed",i:"agreeing",obj:""}, {name:"answer",jp:"答える",p:"answered",i:"answering"},
    {name:"arrive",jp:"到着する",p:"arrived",i:"arriving",m:"eを取る",obj:""}, {name:"ask",jp:"尋ねる",p:"asked",i:"asking"},
    {name:"become",jp:"なる",p:"became",i:"becoming",m:"eを取る",obj:""}, {name:"begin",jp:"始める",p:"began",i:"beginning",m:"nを重ねる"},
    {name:"believe",jp:"信じる",p:"believed",i:"believing",m:"eを取る"}, {name:"call",jp:"呼ぶ",p:"called",i:"calling"},
    {name:"carry",jp:"運ぶ",p:"carried",i:"carrying",m:"y→i"}, {name:"catch",jp:"捕まえる",p:"caught",i:"catching",obj:""},
    {name:"change",jp:"変える",p:"changed",i:"changing",m:"eを取る"}, {name:"clean",jp:"掃除する",p:"cleaned",i:"cleaning"},
    {name:"close",jp:"閉める",p:"closed",i:"closing",m:"eを取る"}, {name:"cry",jp:"泣く",p:"cried",i:"crying",m:"y→i",obj:""},
    {name:"dance",jp:"踊る",p:"danced",i:"dancing",m:"eを取る",obj:""}, {name:"decide",jp:"決める",p:"decided",i:"deciding",m:"eを取る"},
    {name:"drink",jp:"飲む",p:"drank",i:"drinking"}, {name:"drive",jp:"運転する",p:"drove",i:"driving",m:"eを取る"},
    {name:"enjoy",jp:"楽しむ",p:"enjoyed",i:"enjoying"}, {name:"feel",jp:"感じる",p:"felt",i:"feeling"},
    {name:"finish",jp:"終える",p:"finished",i:"finishing"}, {name:"fly",jp:"飛ぶ",p:"flew",i:"flying",obj:""},
    {name:"forget",jp:"忘れる",p:"forgot",i:"forgetting",m:"tを重ねる"}, {name:"give",jp:"与える",p:"gave",i:"giving",m:"eを取る"},
    {name:"hear",jp:"聞こえる",p:"heard",i:"hearing"}, {name:"help",jp:"助ける",p:"helped",i:"helping"},
    {name:"hope",jp:"望む",p:"hoped",i:"hoping",m:"eを取る"}, {name:"invite",jp:"招待する",p:"invited",i:"inviting",m:"eを取る"},
    {name:"join",jp:"参加する",p:"joined",i:"joining",obj:""}, {name:"keep",jp:"保つ",p:"kept",i:"keeping"},
    {name:"know",jp:"知る",p:"knew",i:"knowing"}, {name:"laugh",jp:"笑う",p:"laughed",i:"laughing",obj:""},
    {name:"learn",jp:"学ぶ",p:"learned",i:"learning"}, {name:"leave",jp:"去る",p:"left",i:"leaving",m:"eを取る",obj:""},
    {name:"look",jp:"見る",p:"looked",i:"looking"}, {name:"meet",jp:"会う",p:"met",i:"meeting"},
    {name:"move",jp:"動く",p:"moved",i:"moving",m:"eを取る",obj:""}, {name:"need",jp:"必要とする",p:"needed",i:"needing"},
    {name:"open",jp:"開ける",p:"opened",i:"opening"}, {name:"pay",jp:"払う",p:"paid",i:"paying"},
    {name:"plan",jp:"計画する",p:"planned",i:"planning",m:"nを重ねる"}, {name:"play",jp:"遊ぶ",p:"played",i:"playing"},
    {name:"practice",jp:"練習する",p:"practiced",i:"practicing",m:"eを取る"}, {name:"produce",jp:"生産する",p:"produced",i:"producing",m:"eを取る"},
    {name:"promise",jp:"約束する",p:"promised",i:"promising",m:"eを取る",obj:""}, {name:"protect",jp:"守る",p:"protected",i:"protecting"},
    {name:"put",jp:"置く",p:"put",i:"putting",m:"tを重ねる"}, {name:"rain",jp:"雨が降る",p:"rained",i:"raining",obj:"",subject:"It"},
    {name:"read",jp:"読む",p:"read",i:"reading"}, {name:"remember",jp:"覚える",p:"remembered",i:"remembering"},
    {name:"run",jp:"走る",p:"ran",i:"running",m:"nを重ねる",obj:""}, {name:"say",jp:"言う",p:"said",i:"saying"},
    {name:"see",jp:"見える",p:"saw",i:"seeing"}, {name:"show",jp:"見せる",p:"showed",i:"showing"},
    {name:"sign",jp:"署名する",p:"signed",i:"signing"}, {name:"solve",jp:"解決する",p:"solved",i:"solving",m:"eを取る"},
    {name:"sound",jp:"聞こえる",p:"sounded",i:"sounding",obj:"good"}, {name:"step",jp:"踏む",p:"stepped",i:"stepping",m:"pを重ねる"},
    {name:"stop",jp:"止める",p:"stopped",i:"stopping",m:"pを重ねる"},
    {name:"store",jp:"保存する",p:"stored",i:"storing",m:"eを取る"}, {name:"support",jp:"支持する",p:"supported",i:"supporting"},
    {name:"surprise",jp:"驚かせる",p:"surprised",i:"surprising",m:"eを取る"}, {name:"taste",jp:"味わう",p:"tasted",i:"tasting",m:"eを取る"},
    {name:"test",jp:"試験する",p:"tested",i:"testing"}, {name:"thank",jp:"感謝する",p:"thanked",i:"thanking"},
    {name:"tie",jp:"結ぶ",p:"tied",i:"tying",m:"ie→y"}, {name:"touch",jp:"触れる",p:"touched",i:"touching"},
    {name:"travel",jp:"旅行する",p:"traveled",i:"traveling",obj:""}, {name:"treat",jp:"扱う",p:"treated",i:"treating"},
    {name:"trust",jp:"信頼する",p:"trusted",i:"trusting",obj:""},
    {name:"sing",jp:"歌う",p:"sang",i:"singing"}, {name:"sit",jp:"座る",p:"sat",i:"sitting",m:"tを重ねる",obj:""},
    {name:"sleep",jp:"眠る",p:"slept",i:"sleeping",obj:""}, {name:"smile",jp:"微笑む",p:"smiled",i:"smiling",m:"eを取る",obj:""},
    {name:"speak",jp:"話す",p:"spoke",i:"speaking"}, {name:"stand",jp:"立つ",p:"stood",i:"standing",obj:""},
    {name:"start",jp:"始める",p:"started",i:"starting"}, {name:"stay",jp:"滞在する",p:"stayed",i:"staying",obj:""},
    {name:"study",jp:"勉強する",p:"studied",i:"studying",m:"y→i"},
    {name:"swim",jp:"泳ぐ",p:"swam",i:"swimming",m:"mを重ねる",obj:""}, {name:"take",jp:"取る",p:"took",i:"taking",m:"eを取る"},
    {name:"talk",jp:"話す",p:"talked",i:"talking"}, {name:"teach",jp:"教える",p:"taught",i:"teaching"},
    {name:"tell",jp:"伝える",p:"told",i:"telling"}, {name:"think",jp:"考える",p:"thought",i:"thinking"},
    {name:"try",jp:"試みる",p:"tried",i:"trying",m:"y→i"}, {name:"turn",jp:"曲がる",p:"turned",i:"turning"},
    {name:"understand",jp:"理解する",p:"understood",i:"understanding"}, {name:"use",jp:"使う",p:"used",i:"using",m:"eを取る"},
    {name:"wait",jp:"待つ",p:"waited",i:"waiting",obj:""}, {name:"walk",jp:"歩く",p:"walked",i:"walking",obj:""},
    {name:"want",jp:"欲しがる",p:"wanted",i:"wanting"}, {name:"wash",jp:"洗う",p:"washed",i:"washing"},
    {name:"watch",jp:"見る",p:"watched",i:"watching"}, {name:"win",jp:"勝つ",p:"won",i:"winning",m:"nを重ねる"},
    {name:"work",jp:"働く",p:"worked",i:"working",obj:""}, {name:"write",jp:"書く",p:"wrote",i:"writing",m:"eを取る"}
];